# Generated by Django 2.2.1 on 2019-05-22 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='est_time',
        ),
    ]
