# Generated by Django 2.2.1 on 2019-06-06 19:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('experts', '__first__'),
        ('services', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True, max_length=100)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='services.Service')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='experts.Expert')),
            ],
        ),
    ]
