# Generated by Django 2.2.1 on 2019-05-22 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0002_auto_20190520_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='expert',
            name='position',
            field=models.CharField(default='stylist', max_length=50),
        ),
    ]
